#!/bin/sh
# DebWrt - Debian on Embedded devices
#
# Copyright (C) 2011 Johan van Zoomeren <amain@debwrt.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

ACTION=$1
VERSION=$2

case ${ACTION} in
    configure)
       if ! cat /etc/modules 2>/dev/null | grep -q -e "^wl" -e "^#\W*wl"; then
          cat >>/etc/modules <<EOF
# DebWrt - default is to use the proprietary wl driver
#          there are still performance problems with the open source b43 driver in AP mode
#          uncomment to use broadcom
#          ( note: also unblacklist b43 in /etc/modprobe.d/b43.conf )
wl
EOF
       fi
    ;;
    *)
    ;;
esac

